
info:
  author: Sanjeet
  version: 1.0
  
management:  
  endpoints:
    web:
      exposure:
        include:
        - "*"
  server:
    port: 9090
  endpoint:
    health:
      show-details: "ALWAYS"
    shutdown:
      enabled: true
